{
    "name": "Kaizen Theme",
    "category": "Theme/Corporate",
    "version": "13.0.1.0.0",
    "images": ["static/description/poster.png", "static/description/main.gif"],
    "author": "Onestein, Odoo Community Association (OCA)",
    "depends": ["website", "website_blog"],
    "data": [
        "templates/assets.xml",
        "templates/layout.xml",
        "templates/blog.xml",
        "templates/snippets/menu_1.xml",
        "templates/snippets/menu_2.xml",
        "templates/snippets/menu_3.xml",
        "templates/snippets/hero_1.xml",
        "templates/snippets/devices.xml",
        "templates/snippets/contributors.xml",
        "templates/snippets/media.xml",
        "templates/snippets/media_alt.xml",
        "templates/snippets/design.xml",
        "templates/snippets/posts.xml",
        "templates/snippets/breadcrumbs.xml",
        "templates/snippets/faq.xml",
        "templates/snippets/sidebar.xml",
        "templates/snippets/links.xml",
        "templates/snippets/discussions.xml",
        "templates/snippets/content_listing.xml",
        "templates/snippets.xml",
        "templates/snippet_options.xml",
        "templates/colorpicker.xml",
        "views/theme_customize.xml",
    ],
    "license": "AGPL-3",
}
